export const LoginFormConstant = [
  {
    type: 'input',
    subType: 'text',
    id: 'inputEmail',
    label: 'Email',
    placeholder: 'Email',
    key: 'email',
    required: true,
    class: 'col-12',
  },
  {
    type: 'input',
    subType: 'password',
    id: 'inputPassword',
    label: 'Password',
    placeholder: 'Password',
    key: 'password',
    required: true,
    class: 'col-12',
  },
];

export const SigninFormConstant = [
  {
    type: 'input',
    subType: 'text',
    id: 'inputName',
    label: 'Name',
    placeholder: 'Enter Name',
    key: 'name',
    required: true,
    class: 'col-12',
  },
  {
    type: 'input',
    subType: 'text',
    id: 'inputEmail',
    label: 'Email',
    placeholder: 'Email',
    key: 'email',
    required: true,
    class: 'col-12',
  },
  {
    type: 'phone',
    subType: 'text',
    id: 'inputPhone',
    label: 'Phone',
    placeholder: 'Phone',
    key: 'phone',
    format: '(###) ###-####',
    prefix: '+91',
    required: true,
    class: 'col-12',
  },
  {
    type: 'input',
    subType: 'password',
    id: 'inputPassword',
    label: 'Password',
    placeholder: 'Password',
    key: 'password',
    required: true,
    class: 'col-12',
  },
  {
    type: 'input',
    subType: 'password',
    id: 'inputConfirmPassword',
    label: 'Confirm Password',
    placeholder: 'Confirm Password',
    key: 'confirm_password',
    required: true,
    class: 'col-12',
  },
];
